BEGIN
DECLARE @NOME VARCHAR(50)
SET @NOME = 'TES'
SELECT * FROM PESSOA WHERE RAZAO_SOCIAL LIKE @NOME + '%'
END

--BEGIN
--DECLARE @NOME NVACHAR
--DECLARE @RAZAO_SOCIAL NVARCHAR
--DECLARE @CPF_CNPJ BIGINT
--DECLARE @INSCRICAO_ESTADUAL BIGINT
--DECLARE @ENDERECO_EMAIL NVARCHAR
--DECLARE @STATUS BIT
--DECLARE @OBSERVACAO NVARCHAR

--SET @NOME = "ALGODAOES SANTO GOD"
--SET @RAZAO_SOCIAL = "ASG S/A"
--SET @CPF_CNPJ = "2156454641"
--SET @INSCRICAO_ESTADUAL = "154154515"
--SET @ENDERECO_EMAIL = "vendas@algodaosg.com"
--SET @STATUS = 1
--SET @OBSERVACAO = "FAZER PÓS VENDA PERIODICAMENTE CLIENTE COMPRA BASTANTE"
--END
--GO


BEGIN
DECLARE @ID_CONTRATO INT
DECLARE @ID_STATUS INT
DECLARE @QUANTIDADE FLOAT
DECLARE @VALOR_TOTAL FLOAT
DECLARE @ICMS FLOAT
DECLARE @COND_PAGAMENTO NVARCHAR(30)
DECLARE @SAFRA NVARCHAR(10)
DECLARE @FARDOS INT
DECLARE @LOTE INT
DECLARE @TIPO_FOLHA INT
DECLARE @COR INT
DECLARE @PRECO_NEGOCIADO FLOAT

INSERT INTO PRODUTO_CONTRATO (ID_CONTRATO, ID_STATUS, QUANTIDADE, VALOR_TOTAL, ICMS, COND_PAGAMENTO, FARDOS, LOTE, COR, TIPO_FOLHA, PRECO_NEGOCIADO, SAFRA) VALUES (@ID_CONTRATO, @ID_STATUS, @QUANTIDADE, @VALOR_TOTAL, @ICMS, @COND_PAGAMENTO, @FARDOS, @LOTE, @COR, @TIPO_FOLHA, @PRECO_NEGOCIADO, @SAFRA)
UPDATE PRODUTO_CONTRATO SET ID_CONTRATO=@ID_CONTRATO, ID_STATUS=@ID_STATUS, QUANTIDADE=@QUANTIDADE, VALOR_TOTAL=@VALOR_TOTAL, ICMS=@ICMS, COND_PAGAMENTO=@COND_PAGAMENTO, FARDOS=@FARDOS, LOTE=@LOTE, COR=@COR, TIPO_FOLHA=@TIPO_FOLHA, PRECO_NEGOCIADO=@PRECO_NEGOCIADO, SAFRA=@SAFRA
SELECT ID_CONTRATO, ID_STATUS, QUANTIDADE, VALOR_TOTAL, ICMS, COND_PAGAMENTO, FARDOS, LOTE, COR, TIPO_FOLHA, PRECO_NEGOCIADO, SAFRA WHERE ID_PRODUTO_CONTRATO = @ID_PRODUTO_CONTRATO
END
GO

TRUNCATE TABLE COTTONFIX_FINAL.dbo.VENDEDOR
DROP TABLE PRODUTO

USE COTTONFIX_FINAL
GO
INSERT INTO CLIENTE(ID_CLIENTE) VALUES (3)
SELECT P.ID_PESSOA, P.NOME, P.RAZAO_SOCIAL, P.CPF_CNPJ, P.INSCRICAO_ESTADUAL, P.ENDERECO_EMAIL, P.STATUS, P.OBSERVACAO FROM PESSOA AS P INNER JOIN CLIENTE AS C ON P.ID_PESSOA = C.ID_CLIENTE WHERE C.ID_CLIENTE = 4

INSERT INTO CONTRATO (ID_CONTRATO_STATUS, ID_CLIENTE, ID_VENDEDOR, NUMERO, ID_USUARIO, REGISTRO_BBM, CONDICAO_PAGAMENTO, OBSERVACAO, ENDERECO_CLI, VALOR_TOTAL, EMBARQUE, DATA, ORIGEM, ENDERECO_COBRANCA, ENDERECO_ENTREGA, RETIRADA, ENDERECO_VEN) VALUES (1,4,5,'1111/2017',1,1, 'asasa','sasasa', 'ssasa', '3213','dsadsa', '25/06/2017 15:58:12', 'dsad', 'dasdas', 'dasdas', 'dasdsa', 'dsadsadas')
UPDATE CONTRATO SET ID_CONTRATO = @ID_CONTRATO, ID_CONTRATO_STATUS = @ID_CONTRATO_STATUS, ID_CLIENTE = @ID_CLIENTE, ID_VENDEDOR = @ID_VENDEDOR, NUMERO = @NUMERO, ID_USUARIO = @ID_USUARIO, REGISTRO_BBM = @REGISTRO_BBM, CONDICAO_PAGAMENTO = @CONDICAO_PAGAMENTO, OBSERVACAO = @OBSERVACAO, ENDERECO_CLI = @ENDERECO_CLI, VALOR_TOTAL = @VALOR_TOTAL, EMBARQUE = @EMBARQUE, DATA = @DATA, ORIGEM = @ORIGEM, ENDERECO_COBRANCA = @ENDERECO_COBRANCA, ENDERECO_ENTREGA = @ENDERECO_ENTREGA, RETIRADA = @RETIRADA, ENDERECO_VEN = @ENDERECO_VEN WHERE ID_CONTRATO = @ID_CONTRATO
UPDATE CONTRATO SET ID_CONTRATO_STATUS = @ID_CONTRATO_STATUS WHERE ID_CONTRATO = @ID_CONTRATO
SELECT * FROM CONTRATO WHERE ID_CONTRATO = @ID_CONTRATO

INSERT INTO CONTRATO_STATUS VALUES ('ABERTO')
INSERT INTO CONTRATO_STATUS VALUES ('LIQUIDADO')
INSERT INTO CONTRATO_STATUS VALUES ('CANCEELADO')
INSERT INTO CONTRATO_STATUS VALUES ('PENDENTE')
INSERT INTO CONTRATO_STATUS VALUES ('EMBARCADA')
INSERT INTO CONTRATO_STATUS VALUES ('ENTREGUE')
INSERT INTO CONTRATO_STATUS VALUES ('AGUARDANDO EMBARQUE')


UPDATE CONTRATO_STATUS SET DESCRICAO = 'CANCELADO' WHERE ID_CONTRATO_STATUS = 3
INSERT INTO CONTRATO VALUES (1,4,5,'1',1,1,'a','a', 'a', 3,'a', '25/06/2017', 'a', 'a', 'a', 'a', 'a')

INSERT INTO ACESSO VALUES ('ADMINISTRADOR')
INSERT INTO ACESSO VALUES ('CORRETOR')

SELECT MAX(ID_CONTRATO) FROM CONTRATO

ALTER TABLE CONTRATO ALTER COLUMN NUMERO INT NULL

SELECT * FROM USUARIO WHERE LOGIN = 'AA44' 

SELECT * FROM CONTRATO WHERE ID_CONTRATO = 14