//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.PRODUTO_CONTRATO = new HashSet<PRODUTO_CONTRATO>();
        }
    
        public int ID_CONTRATO { get; set; }
        public int ID_CONTRATO_STATUS { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_VENDEDOR { get; set; }
        public string NUMERO { get; set; }
        public Nullable<int> REGISTRO_BBM { get; set; }
        public string COND_PAGAMENTO { get; set; }
        public string OBSERVACAO { get; set; }
        public string ENDERECO_CLI { get; set; }
        public string ENDERECO_VEN { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual CONTRATO_STATUS CONTRATO_STATUS { get; set; }
        public virtual VENDEDOR VENDEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_CONTRATO> PRODUTO_CONTRATO { get; set; }
    }
}
