//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENDERECO
    {
        public int ID_ENDERECO { get; set; }
        public Nullable<int> ID_PESSOA { get; set; }
        public string DESCRICAO { get; set; }
        public string RUA { get; set; }
        public int NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string COMPLEMENTO { get; set; }
        public int CEP { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string OBSERVACAO { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
