//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloCottonFixBD : DbContext
    {
        public ModeloCottonFixBD()
            : base("name=ModeloCottonFixBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACESSO> ACESSO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<CONTRATO_STATUS> CONTRATO_STATUS { get; set; }
        public virtual DbSet<ENDERECO> ENDERECO { get; set; }
        public virtual DbSet<PESSOA> PESSOA { get; set; }
        public virtual DbSet<PRODUTO> PRODUTO { get; set; }
        public virtual DbSet<PRODUTO_CONTRATO> PRODUTO_CONTRATO { get; set; }
        public virtual DbSet<PRODUTO_COR> PRODUTO_COR { get; set; }
        public virtual DbSet<PRODUTO_FIBRA> PRODUTO_FIBRA { get; set; }
        public virtual DbSet<STATUS_VENDA> STATUS_VENDA { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TELEFONE> TELEFONE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VENDEDOR> VENDEDOR { get; set; }
    }
}
