//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_COR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO_COR()
        {
            this.PRODUTO_CONTRATO = new HashSet<PRODUTO_CONTRATO>();
        }
    
        public int PRODUTO_COR_ID { get; set; }
        public string DESCRICAO { get; set; }
        public int BASE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_CONTRATO> PRODUTO_CONTRATO { get; set; }
    }
}
