//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_CONTRATO
    {
        public int ID_PRODUTO_CONTRATO { get; set; }
        public int ID_CONTRATO { get; set; }
        public int ID_PRODUTO { get; set; }
        public int ID_PRODUTO_FIBRA { get; set; }
        public int ID_PRODUTO_COR { get; set; }
        public int ID_STATUS_VENDA { get; set; }
        public double QTD { get; set; }
        public double VALOR_UNITARIO { get; set; }
        public Nullable<double> ICMS { get; set; }
        public Nullable<System.DateTime> DATA_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DATA_EMBAR_PREV { get; set; }
        public Nullable<System.DateTime> DATA_ENTREGA { get; set; }
        public Nullable<System.DateTime> DATA_EMBARQUE_PREV { get; set; }
        public string COND_PAGAMENTO { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> FARDOS { get; set; }
        public Nullable<int> LOTE { get; set; }
        public string ENDERECO_CLI { get; set; }
        public string ENDERECO_VEN { get; set; }
        public string SAFRA { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual PRODUTO_COR PRODUTO_COR { get; set; }
        public virtual PRODUTO_FIBRA PRODUTO_FIBRA { get; set; }
        public virtual STATUS_VENDA STATUS_VENDA { get; set; }
    }
}
