//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.PRODUTO_CONTRATO = new HashSet<PRODUTO_CONTRATO>();
        }
    
        public int ID_PRODUTO { get; set; }
        public string DESCRICAO { get; set; }
        public int TIPO { get; set; }
        public Nullable<int> V12 { get; set; }
        public Nullable<int> V3 { get; set; }
        public Nullable<int> V4 { get; set; }
        public Nullable<int> V5 { get; set; }
        public Nullable<int> V6 { get; set; }
        public Nullable<int> V7 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_CONTRATO> PRODUTO_CONTRATO { get; set; }
    }
}
