//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE
    {
        public int ID_TELEFONE { get; set; }
        public int ID_PESSOA { get; set; }
        public string DESCRICAO { get; set; }
        public long TELEFONE1 { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
    }
}
