//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ID_ACESSO { get; set; }
        public string EMAIL { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string SMTP { get; set; }
        public Nullable<int> PORTA { get; set; }
        public Nullable<long> TELEFONE { get; set; }
    
        public virtual ACESSO ACESSO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
    }
}
