//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelCottonFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEDOR()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public int ID_VENDEDOR { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public Nullable<long> CPFCNPJ { get; set; }
        public Nullable<long> INSCRICAO_ESTADUAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        public virtual PESSOA PESSOA { get; set; }
    }
}
